// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pass_through/pass_through.proto

package pass_through

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassThroughConnection_StatusCode int32

const (
	PassThroughConnection_TASK_WAITING PassThroughConnection_StatusCode = 0
	PassThroughConnection_TASK_RUNNING PassThroughConnection_StatusCode = 1
	PassThroughConnection_TASK_OVER    PassThroughConnection_StatusCode = 2
)

var PassThroughConnection_StatusCode_name = map[int32]string{
	0: "TASK_WAITING",
	1: "TASK_RUNNING",
	2: "TASK_OVER",
}

var PassThroughConnection_StatusCode_value = map[string]int32{
	"TASK_WAITING": 0,
	"TASK_RUNNING": 1,
	"TASK_OVER":    2,
}

func (x PassThroughConnection_StatusCode) String() string {
	return proto.EnumName(PassThroughConnection_StatusCode_name, int32(x))
}

func (PassThroughConnection_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de0e8917fb46342e, []int{0, 0}
}

// 建立转发链接
type PassThroughConnection struct {
	GrpcSrvId            string               `protobuf:"bytes,1,opt,name=grpc_srv_id,json=grpcSrvId,proto3" json:"grpc_srv_id,omitempty"`
	GrpcClientId         string               `protobuf:"bytes,2,opt,name=grpc_client_id,json=grpcClientId,proto3" json:"grpc_client_id,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status               int32                `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PassThroughConnection) Reset()         { *m = PassThroughConnection{} }
func (m *PassThroughConnection) String() string { return proto.CompactTextString(m) }
func (*PassThroughConnection) ProtoMessage()    {}
func (*PassThroughConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_de0e8917fb46342e, []int{0}
}

func (m *PassThroughConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassThroughConnection.Unmarshal(m, b)
}
func (m *PassThroughConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassThroughConnection.Marshal(b, m, deterministic)
}
func (m *PassThroughConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassThroughConnection.Merge(m, src)
}
func (m *PassThroughConnection) XXX_Size() int {
	return xxx_messageInfo_PassThroughConnection.Size(m)
}
func (m *PassThroughConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_PassThroughConnection.DiscardUnknown(m)
}

var xxx_messageInfo_PassThroughConnection proto.InternalMessageInfo

func (m *PassThroughConnection) GetGrpcSrvId() string {
	if m != nil {
		return m.GrpcSrvId
	}
	return ""
}

func (m *PassThroughConnection) GetGrpcClientId() string {
	if m != nil {
		return m.GrpcClientId
	}
	return ""
}

func (m *PassThroughConnection) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *PassThroughConnection) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterEnum("pass_through.PassThroughConnection_StatusCode", PassThroughConnection_StatusCode_name, PassThroughConnection_StatusCode_value)
	proto.RegisterType((*PassThroughConnection)(nil), "pass_through.PassThroughConnection")
}

func init() { proto.RegisterFile("pass_through/pass_through.proto", fileDescriptor_de0e8917fb46342e) }

var fileDescriptor_de0e8917fb46342e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0x33, 0x75, 0xd0, 0xd7, 0x2a, 0x25, 0xa0, 0x94, 0x1d, 0x5c, 0x19, 0x1e, 0x7a,
	0x6a, 0x41, 0x8f, 0x1e, 0x64, 0x14, 0x91, 0x22, 0x54, 0x49, 0xab, 0x1e, 0x43, 0xd6, 0xc6, 0xae,
	0xb0, 0x35, 0x25, 0x49, 0xf7, 0xc5, 0xfd, 0x02, 0x92, 0xd4, 0x8d, 0xde, 0xf2, 0x7e, 0xef, 0x1f,
	0xde, 0x1f, 0x96, 0x3d, 0x53, 0x8a, 0xea, 0xad, 0x14, 0x43, 0xb3, 0x4d, 0xa6, 0x43, 0xdc, 0x4b,
	0xa1, 0x05, 0xf6, 0xa6, 0xb6, 0x58, 0x36, 0x42, 0x34, 0x3b, 0x9e, 0xd8, 0xdd, 0x66, 0xf8, 0x49,
	0x74, 0xbb, 0xe7, 0x4a, 0xb3, 0x7d, 0x3f, 0xc6, 0x57, 0xbf, 0x08, 0x6e, 0x3e, 0x98, 0x52, 0xe5,
	0xf8, 0x21, 0x15, 0x5d, 0xc7, 0x2b, 0xdd, 0x8a, 0x0e, 0xdf, 0x81, 0xdb, 0xc8, 0xbe, 0xa2, 0x4a,
	0x1e, 0x68, 0x5b, 0x07, 0x28, 0x44, 0x91, 0x43, 0x1c, 0x43, 0x85, 0x3c, 0x64, 0x35, 0xbe, 0x87,
	0x6b, 0xbb, 0xaf, 0x76, 0x2d, 0xef, 0xb4, 0x89, 0xcc, 0x6c, 0xc4, 0x33, 0x9a, 0x5a, 0xcc, 0x6a,
	0xfc, 0x04, 0x6e, 0x25, 0x39, 0xd3, 0x9c, 0x9a, 0xcb, 0xc1, 0x79, 0x88, 0x22, 0xf7, 0x61, 0x11,
	0x8f, 0xb5, 0xe2, 0x63, 0xad, 0xb8, 0x3c, 0xd6, 0x22, 0x30, 0xc6, 0x0d, 0xe0, 0x5b, 0x98, 0x2b,
	0xcd, 0xf4, 0xa0, 0x82, 0x8b, 0x10, 0x45, 0x97, 0xe4, 0x7f, 0x5a, 0x3d, 0x03, 0x14, 0xf6, 0x95,
	0x8a, 0x9a, 0x63, 0x1f, 0xbc, 0x72, 0x5d, 0xbc, 0xd1, 0xef, 0x75, 0x56, 0x66, 0xf9, 0xab, 0x7f,
	0x76, 0x12, 0xf2, 0x99, 0xe7, 0x46, 0x10, 0xbe, 0x02, 0xc7, 0xca, 0xfb, 0xd7, 0x0b, 0xf1, 0x67,
	0x9b, 0xb9, 0x3d, 0xfc, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x78, 0x52, 0xdf, 0x4e, 0x01,
	0x00, 0x00,
}
